import Head from "next/head";
import { CitySelector, ItemList, ListContainer } from "../../styles/List";
import Image from "next/image";
import { useRouter } from "next/router";
import { useEffect, useState } from "react";
import { listStoreByCategoryController } from "../../controllers/Restaurants.controller";
import { IStores } from "../../interfaces/IStores";
import Loader from "../../components/Loader";
import { calcRating } from "../../utils/calcRating";

export default function Home() {
  const [restaurants, setRestaurants] = useState<IStores[]>([]);
  const [filterBy, setFilterBy] = useState("");
  const [loading, setLoading] = useState(true);
  const [citySelected, setCitySelected] = useState("");

  const router = useRouter();
  const { category } = router.query;

  useEffect(() => {
    if (router.isReady) {
      loadData();
    }
  }, [router.isReady, citySelected]);

  const loadData = async () => {
    const result = await listStoreByCategoryController(`${category}`, citySelected);
    setRestaurants(result);
    setLoading(false);
  };

  const handleClick = (id: string) => {
    router.push(`/restaurant/${id}`);
  };

  const handleGoBack = () => {
    router.push(`/list`);
  };

  return (
    <>
      <Head>
        <title>Urunga - Category</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <ListContainer>
        <Image
          src={"/icons/back.svg"}
          alt={"go back"}
          height={30}
          width={30}
          className="back-icon"
          onClick={handleGoBack}
        />
        <Image
          src={"/logo.svg"}
          alt={"RatingStar"}
          height={88}
          width={88}
          className="logo-icon"
        />
         <CitySelector>
          <select
            name="cars"
            id="cars"
            value={citySelected}
            onChange={(e) => setCitySelected(e.target.value)}
          >
            <option value="" disabled>
              Escolha sua Cidade
            </option>
            <option value="jundiai">Jundiaí</option>
            <option value="varzeapta">Várzea Paulista</option>
            <option value="campolimpopta">Campo Limpo Paulista</option>
          </select>
        </CitySelector>

        <div className="search-bar">
          <Image
            src={"/icons/question-mark.svg"}
            alt={"RatingStar"}
            height={15}
            width={15}
          />

          <input
            type="text"
            placeholder="Pesquisar restaurante"
            value={filterBy}
            onChange={(e) => setFilterBy(e.target.value)}
          />
        </div>

        <br />

        <ItemList>
          <h2>Restaurantes</h2>
          {loading ? (
            <div className="loaderContainer">
              <Loader />
            </div>
          ) : (
            <>
              <ul>
                {restaurants
                  .filter((item) =>
                    item.name.toLowerCase().includes(filterBy.toLowerCase())
                  )
                  .map((item) => {
                    return (
                      <li key={item._id} onClick={() => handleClick(item._id)}>
                        <div className="image-holder">
                          <Image
                            src={item.logo}
                            alt={"RatingStar"}
                            height={88}
                            width={88}
                          />
                        </div>
                        <div className="info-box">
                          <p>{item.name}</p>
                          <span>{item.description}</span>
                          <div className="ratings">
                            <Image
                              src={"/icons/start.svg"}
                              alt={"RatingStar"}
                              height={10}
                              width={10}
                            />
                            <label>{calcRating(item)}</label>
                            <small>({item.rating.length} avaliações)</small>
                          </div>
                        </div>
                      </li>
                    );
                  })}
              </ul>
              {restaurants.filter((item) =>
                item.name.toLowerCase().includes(filterBy.toLowerCase())
              ).length === 0 && <p>Nenhum Restaurante encontrado</p>}
            </>
          )}
        </ItemList>
      </ListContainer>
    </>
  );
}
