import Head from "next/head";
import { ItemList, ListContainer, Categories } from "../styles/List";
import Image from "next/image";
import { useRouter } from "next/router";
import { useEffect, useState } from "react";
import { listStoresController } from "../controllers/Restaurants.controller";
import { IStores } from "../interfaces/IStores";

export default function Home() {
  const router = useRouter();
  const [restaurants, setRestaurants] = useState<IStores[]>([]);
  const [filterBy, setFilterBy] = useState("");

  useEffect(() => {
    loadData();
  }, []);

  const loadData = async () => {
    const result = await listStoresController();
    setRestaurants(result);
  };

  const handleClick = (id: string) => {
    router.push(`/restaurant/${id}`);
  };

  const handleCategory = (title: string) => {
    router.push(`/category/${title}`);
  };

  const categories = [
    {
      color: "orange",
      title: "Lanches",
      image: "hamburguer.svg",
      api: "burguer",
    },
    {
      color: "blue",
      title: "Pizzarias",
      image: "pizzaria.svg",
      api: "pizza",
    },
    {
      color: "purple",
      title: "Bebidas",
      image: "drink.png",
      api: "drink",
    },
    {
      color: "red",
      title: "Carnes",
      image: "meat.svg",
      api: "meat",
    },
  ];

  return (
    <>
      <Head>
        <title>Urunga - List</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <ListContainer>
        <Image
          src={"/logo.svg"}
          alt={"RatingStar"}
          height={88}
          width={88}
          className="logo-icon"
        />
        <div className="search-bar">
          <Image
            src={"/icons/question-mark.svg"}
            alt={"RatingStar"}
            height={15}
            width={15}
          />

          <input
            type="text"
            placeholder="Pesquisar restaurante"
            value={filterBy}
            onChange={(e) => setFilterBy(e.target.value)}
          />
        </div>

        <Categories>
          <h2>Categorias</h2>
          <div className="category-group">
            {categories.map((item, index) => {
              return (
                <div
                  key={index}
                  className="category-item"
                  onClick={() => handleCategory(item.api)}
                >
                  <div className={item.color}>
                    <Image
                      src={`/icons/${item.image}`}
                      alt={item.title}
                      height={40}
                      width={40}
                    />
                  </div>
                  <p>{item.title}</p>
                </div>
              );
            })}
          </div>
        </Categories>

        <ItemList>
          <h2>Restaurantes</h2>
          <ul>
            {restaurants
              .filter((item) =>
                item.name.toLowerCase().includes(filterBy.toLowerCase())
              )
              .map((item) => {
                return (
                  <li key={item._id} onClick={() => handleClick(item._id)}>
                    <div className="image-holder">
                      <Image
                        src={item.logo}
                        alt={"RatingStar"}
                        height={88}
                        width={88}
                      />
                    </div>
                    <div className="info-box">
                      <p>{item.name}</p>
                      <span>{item.description}</span>
                      <div className="ratings">
                        <Image
                          src={"/icons/start.svg"}
                          alt={"RatingStar"}
                          height={10}
                          width={10}
                        />
                        <label>4.8</label>
                        <small>(5 ratings)</small>
                      </div>
                    </div>
                  </li>
                );
              })}
          </ul>
          {restaurants.filter((item) =>
            item.name.toLowerCase().includes(filterBy.toLowerCase())
          ).length === 0 && <p>Nenhum Restaurante encontrado</p>}
        </ItemList>
      </ListContainer>
    </>
  );
}
