import Head from "next/head";
import { ModalContainer, ProfileContainer } from "../styles/Profile";
import Image from "next/image";
import { useRouter } from "next/router";
import Cookies from "js-cookie";
import { Modal, ModalBody } from "reactstrap";
import { useState } from "react";
import { parseJwt } from "../utils/parseJwt";
import { deleteAccountController } from "../controllers/Auth.controller";

export default function Home() {
  const router = useRouter();

  const [modal, setModal] = useState(false);
  const toggle = () => setModal(!modal);

  const handleLogout = () => {
    Cookies.remove("token");
    setTimeout(() => {
      router.push("/");
    }, 300);
  };

  const handleDeleteAccount = async () => {
    const token = Cookies.get("token");
    const parsedToken = parseJwt(`${token}`);
    await deleteAccountController(`${parsedToken.data._id}`);
    handleLogout();
  };

  return (
    <>
      <Head>
        <title>Urunga - List</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <ProfileContainer>
        <Image
          src={"/logo.svg"}
          alt={"RatingStar"}
          height={88}
          width={88}
          className="logo-icon"
        />
        <h2>Perfil</h2>

        <p onClick={toggle}>Excluir conta</p>

        <button type="button" onClick={handleLogout}>
          Sair
        </button>
      </ProfileContainer>
      <Modal isOpen={modal} toggle={toggle} centered>
        <ModalBody>
          <ModalContainer>
            <h2>Tem certeza de que deseja excluir sua conta?</h2>

            <button
              type="button"
              className="delete"
              onClick={handleDeleteAccount}
            >
              Sim, Excluir
            </button>

            <button type="button" onClick={toggle}>
              Não, voltar
            </button>
          </ModalContainer>
        </ModalBody>
      </Modal>
    </>
  );
}
