import Head from "next/head";
import { ProfileContainer } from "../styles/Profile";
import Image from "next/image";
import { useRouter } from "next/router";
import Cookies from "js-cookie";

export default function Home() {
  const router = useRouter();

  const handleLogout = () => {
    Cookies.remove("token");
    setTimeout(() => {
      router.push("/");
    }, 300);
  };

  return (
    <>
      <Head>
        <title>Urunga - List</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <ProfileContainer>
        <Image
          src={"/logo.svg"}
          alt={"RatingStar"}
          height={88}
          width={88}
          className="logo-icon"
        />
        <h2>Perfil</h2>

        <button type="button" onClick={handleLogout}>
          Sair
        </button>
      </ProfileContainer>
    </>
  );
}
