import Head from "next/head";
import { SuccessContainer } from "../styles/Success";
import Image from "next/image";
import { useRouter } from "next/router";

export default function Home() {
  const router = useRouter();

  return (
    <>
      <Head>
        <title>Urunga - List</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <SuccessContainer>
        <Image
          src={"/logo.svg"}
          alt={"RatingStar"}
          height={88}
          width={88}
          className="logo-icon"
        />

        <h1>Assinatura em processamento</h1>

        <p>
          Após processar o pagamento você terá acesso total ao app, até lá
          continue aproveitando o app.
        </p>

        <button type="button" onClick={() => router.push("/list")}>
          Voltar ao app
        </button>
      </SuccessContainer>
    </>
  );
}
