import Cookies from "js-cookie";
import Head from "next/head";
import { useEffect, useState } from "react";
import { QrReader } from "react-qr-reader";
import { listStoreByEmailController } from "../controllers/Restaurants.controller";
import { ValidatorContainer } from "../styles/Validator";
import { parseJwt } from "../utils/parseJwt";
import Image from "next/image";

export default function Home() {
  const [stores, setStores] = useState<any[]>([]);

  useEffect(() => {
    fetchData();
  }, []);

  const fetchData = async () => {
    const JwtToken = Cookies.get("token");
    const token = parseJwt(`${JwtToken}`);
    const data = await listStoreByEmailController(`${token.data.email}`);

    setStores([...data]);
  };

  const validateQrCode = (codeValue: string) => {
    const storeExist = stores.findIndex(
      (item) => item._id === codeValue.split("-")[0]
    );

    if (storeExist) {
      alert("Cupom Valido");
    }
  };

  return (
    <>
      <Head>
        <title>Urunga - Validador</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <ValidatorContainer>
        <Image
          src={"/logo.svg"}
          alt={"RatingStar"}
          height={88}
          width={88}
          className="logo-icon"
        />
        <h1>Leitor de Cupom</h1>
        <QrReader
          onResult={(result: any, _error) => {
            if (result && result.text) {
              validateQrCode(result.text);
            }
          }}
          constraints={{ facingMode: "user" }}
        />
      </ValidatorContainer>
    </>
  );
}
